version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        ports:
            - "15672:15672"
            - "5672:5672"
    server:
        build: 
            context: server
        ports:
            - "5002:5002"
        volumes:
            - data-volume:/data
    worker1:
        build: 
            context: worker
        ports:
            - "5000:5000"
            - "5012:8080"
        volumes:
            - data-volume:/data
        environment:
            - ID=1
    worker2:
        build: 
            context: worker
        ports:
            - "5001:5001"
            - "5011:8080"
        volumes:
            - data-volume:/data
        environment:
            - ID=2

volumes:
    data-volume:
