version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        network_mode: "host"
        ports:
            - "15672:15672"
            - "5672:5672"
    server:
        build: 
            context: server
        network_mode: "host"
        ports:
            - "5002:5002"
    worker1:
        build: 
            context: worker
        network_mode: "host"
        ports:
            - "5000:5000"
            - "5012:8080"
    worker2:
        build: 
            context: worker
        network_mode: "host"
        ports:
            - "5001:5001"
            - "5011:8080"
